### ISSUE TITLE
Incorrect Calculation for Broker Commission

### ISSUE THREAD

**Issue by pmt-it** [pmt-it/Admin#15]
Refer to transaction Payout Ref #: 10100000173

Broker commission calculation is assuming the send currency is the same as payout currency.

Description:
Send agent commission is 30%, CCB payout commission is 35%
Exchange Rate: 1 HKD = 0.09 EUR
Send currency is HKD. Send Fee is 100 HKD.
Payout currency is EUR. Send Fee in Eur is 9 Eur

Calculation
Broker Commission  = Send fee - Send commission - Payout Commission

Current Calc: 66.85 = 100 - 30 - 3.15
Correct Calc: 35 =  100 - 30 - (3.15/0.09)

**Comment by jctopo** [comment]
Fixed

**Comment by pmt-it** [comment]
Not fixed - we are losing decimals in the conversion

I have created the same transaction. The broker commission should be 35 not 34.9960

select \* from dbo.TRAN_BrokerCommission where payoutreferenceid = '10100000174'

**Comment by jctopo** [comment]
Fixed, try with a new transaction

**Comment by pmt-it** [comment]
Verified
